# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload to Read the docs

on: [push, pull_request]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme
        pip install recommonmark
        pip install ruamel.yaml==0.17.21
    - name: Clone caracal repo
      run: git clone https://github.com/caracal-pipeline/caracal.git ../caracal/
    - name: Publish docs
      run: |
        python make_caracal_docs.py
        cd sphinx && make html
        
    - uses: actions/checkout@v4
    - name: Make changes to pull request
      run: date +%s > report.txt

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: example-patches
        delete-branch: true
        title: 'Read the docs updates'
        body: |
          Update report
          - Auto-generated by caracal
        labels: |
          automated pr
        assignees: athanaseus
        reviewers: paoloserra
        draft: false
